{{-- Collect the same validated account fields for create and edit actions. --}}
<div class="grid gap-4 sm:grid-cols-2">
    <label class="grid gap-1.5 text-xs font-semibold">Full name<input name="name" value="{{ old('name', $customer?->name) }}" required class="h-10 border border-slate-200 px-3 font-normal"></label>
    <label class="grid gap-1.5 text-xs font-semibold">Email address<input type="email" name="email" value="{{ old('email', $customer?->email) }}" required class="h-10 border border-slate-200 px-3 font-normal"></label>
    <label class="grid gap-1.5 text-xs font-semibold">Phone number<input name="phone" value="{{ old('phone', $customer?->phone) }}" class="h-10 border border-slate-200 px-3 font-normal"></label>
    <label class="grid gap-1.5 text-xs font-semibold">Role<select name="role" class="h-10 border border-slate-200 px-3 font-normal">@foreach(['customer', 'admin'] as $role)<option value="{{ $role }}" @selected(old('role', $customer?->role ?? 'customer') === $role)>{{ ucfirst($role) }}</option>@endforeach</select></label>
    <label class="grid gap-1.5 text-xs font-semibold">Language<select name="locale" class="h-10 border border-slate-200 px-3 font-normal">@foreach(['km' => 'Khmer', 'en' => 'English', 'zh' => 'Chinese'] as $locale => $label)<option value="{{ $locale }}" @selected(old('locale', $customer?->locale ?? 'en') === $locale)>{{ $label }}</option>@endforeach</select></label>
    <label class="grid gap-1.5 text-xs font-semibold">Status<select name="status" class="h-10 border border-slate-200 px-3 font-normal">@foreach(['active', 'inactive', 'blocked'] as $status)<option value="{{ $status }}" @selected(old('status', $customer?->status ?? 'active') === $status)>{{ ucfirst($status) }}</option>@endforeach</select></label>
    <label class="grid gap-1.5 text-xs font-semibold">Password @if($customer)<span class="font-normal text-slate-400">(leave blank to keep current)</span>@endif<input type="password" name="password" @required(!$customer) class="h-10 border border-slate-200 px-3 font-normal"></label>
    <label class="grid gap-1.5 text-xs font-semibold">Confirm password<input type="password" name="password_confirmation" @required(!$customer) class="h-10 border border-slate-200 px-3 font-normal"></label>
</div>
@if($errors->any())<div class="mt-4 bg-red-50 p-3 text-xs text-red-700"><ul class="list-disc space-y-1 pl-5">@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<div class="mt-5 flex justify-end gap-2"><a data-admin-load href="{{ route('admin.customers.index') }}" class="inline-flex h-9 items-center border border-slate-300 px-4 text-xs font-bold text-slate-600">Cancel</a><button class="h-9 bg-[#173f88] px-5 text-xs font-bold text-white">{{ $submitLabel }}</button></div>
