@extends('admin.layouts.app')
@section('title',$product->exists?'Edit product':'Create product') @section('breadcrumb','Catalog / Products / '.($product->exists?'Edit':'Create'))
@section('content')
@php($translations=$product->translations->keyBy('locale'))
<div class="mb-5 flex items-center justify-between"><div><h1 class="text-xl font-bold">{{ $product->exists?'Edit product':'Create product' }}</h1><p class="mt-1 text-xs text-slate-500">Operational data and three storefront languages.</p></div><a data-admin-load href="{{ route('admin.products.index') }}" class="border border-slate-300 px-4 py-2 text-xs font-bold">← Products</a></div>
<form method="POST" action="{{ $product->exists?route('admin.products.update',$product):route('admin.products.store') }}" enctype="multipart/form-data" class="grid gap-5">@csrf @if($product->exists)@method('PUT')@endif
    {{-- Keep compact operational product fields separate from translated content. --}}
    <section class="border border-slate-200 bg-white p-5 shadow-sm"><h2 class="mb-4 text-sm font-bold">Product information</h2><div class="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <label class="grid gap-1 text-[11px] font-bold">SKU<input name="sku" value="{{ old('sku',$product->sku) }}" required class="h-9 border border-slate-200 px-3 text-xs"></label>
        <label class="grid gap-1 text-[11px] font-bold">Slug<input name="slug" value="{{ old('slug',$product->slug) }}" required class="h-9 border border-slate-200 px-3 text-xs"></label>
        <label class="grid gap-1 text-[11px] font-bold">Category<select name="category_id" required class="h-9 border border-slate-200 px-3 text-xs">@foreach($categories as $category)<option value="{{ $category->id }}" @selected(old('category_id',$product->category_id)==$category->id)>{{ $category->translation('en')?->name }}</option>@endforeach</select></label>
        <label class="grid gap-1 text-[11px] font-bold">Status<select name="status" class="h-9 border border-slate-200 px-3 text-xs">@foreach(['draft','active','inactive','out_of_stock'] as $status)<option value="{{ $status }}" @selected(old('status',$product->status??'draft')===$status)>{{ ucfirst(str_replace('_',' ',$status)) }}</option>@endforeach</select></label>
        <label class="grid gap-1 text-[11px] font-bold">Price<input type="number" step="0.01" name="price" value="{{ old('price',$product->price) }}" required class="h-9 border border-slate-200 px-3 text-xs"></label>
        <label class="grid gap-1 text-[11px] font-bold">Compare price<input type="number" step="0.01" name="compare_at_price" value="{{ old('compare_at_price',$product->compare_at_price) }}" class="h-9 border border-slate-200 px-3 text-xs"></label>
        <label class="grid gap-1 text-[11px] font-bold">Stock<input type="number" name="stock_quantity" value="{{ old('stock_quantity',$product->stock_quantity??0) }}" required class="h-9 border border-slate-200 px-3 text-xs"></label>
        <label class="flex items-end gap-2 pb-2 text-[11px] font-bold"><input type="checkbox" name="is_featured" value="1" @checked(old('is_featured',$product->is_featured))> Featured product</label>
    </div></section>
    {{-- Edit Khmer, English and Chinese in matching language tabs. --}}
    <section class="border border-slate-200 bg-white shadow-sm"><div data-language-tabs class="flex border-b border-slate-200">@foreach([['km','🇰🇭 ខ្មែរ'],['en','🇺🇸 English'],['zh','🇨🇳 中文']] as [$locale,$label])<button type="button" data-language-tab="{{ $locale }}" class="border-b-2 px-5 py-3 text-xs font-bold {{ $loop->first?'is-active':'' }}">{{ $label }}</button>@endforeach</div><div class="p-5">@foreach(['km','en','zh'] as $locale)<div data-language-panel="{{ $locale }}" class="admin-language-panel grid gap-4" @if(!$loop->first) hidden @endif><label class="grid gap-1 text-[11px] font-bold">Product name<input name="translations[{{ $locale }}][name]" value="{{ old("translations.$locale.name",$translations->get($locale)?->name) }}" required class="h-9 border border-slate-200 px-3 text-xs"></label><label class="grid gap-1 text-[11px] font-bold">Short description<textarea name="translations[{{ $locale }}][short_description]" rows="2" class="border border-slate-200 p-3 text-xs">{{ old("translations.$locale.short_description",$translations->get($locale)?->short_description) }}</textarea></label><label class="grid gap-1 text-[11px] font-bold">Description<textarea name="translations[{{ $locale }}][description]" class="admin-rich-editor">{{ old("translations.$locale.description",$translations->get($locale)?->description) }}</textarea></label></div>@endforeach</div></section>
    {{-- Show each saved image with a dedicated delete control. --}}
    <section class="border border-slate-200 bg-white p-5 shadow-sm"><h2 class="text-sm font-bold">Product images</h2>@if($product->images->isNotEmpty())<div class="mt-3 flex flex-wrap gap-3">@foreach($product->images as $image)<div class="group relative size-20 border border-slate-200 bg-white"><img src="{{ $image->url() }}" alt="Product image {{ $loop->iteration }}" class="size-full object-contain"><button type="submit" form="delete-product-image-{{ $image->id }}" class="absolute -right-2 -top-2 grid size-7 place-items-center rounded-full bg-red-500 text-white shadow-lg transition-transform hover:scale-110" aria-label="Delete product image {{ $loop->iteration }}" title="Delete image"><x-admin.icon name="trash" class="size-3.5" /></button>@if($image->is_primary)<span class="absolute bottom-1 left-1 bg-[#173f88] px-1.5 py-0.5 text-[9px] font-bold uppercase text-white">Primary</span>@endif</div>@endforeach</div>@endif<label class="mt-4 grid gap-1 text-[11px] font-bold">Upload images<input type="file" name="images[]" multiple accept="image/jpeg,image/png,image/webp" class="h-9 border border-slate-200 px-2 py-1 text-xs"></label></section>
    <div class="flex justify-end gap-2"><a data-admin-load href="{{ route('admin.products.index') }}" class="grid h-9 place-items-center border border-slate-300 px-5 text-xs font-bold">Cancel</a><button class="h-9 bg-[#173f88] px-6 text-xs font-bold text-white">Save product</button></div>
</form>
{{-- Keep delete forms outside the product form to avoid nested form markup. --}}
@foreach($product->images as $image)<form id="delete-product-image-{{ $image->id }}" method="POST" action="{{ route('admin.products.images.destroy', [$product, $image]) }}" class="hidden" onsubmit="return confirm('Delete this product image?')">@csrf @method('DELETE')</form>@endforeach
@endsection
