@extends('admin.layouts.app')
@section('title','Categories') @section('breadcrumb','Catalog / Categories')
@section('content')
<div class="mb-5"><h1 class="text-xl font-bold">Categories</h1><p class="mt-1 text-xs text-slate-500">Organize storefront products with translated category names.</p></div>
<div class="grid gap-5 xl:grid-cols-[380px_1fr]">
    <form method="POST" action="{{ route('admin.categories.store') }}" class="h-fit border border-slate-200 bg-white p-5 shadow-sm">@csrf<h2 class="text-sm font-bold">Create category</h2><div class="mt-4 grid gap-3"><label class="grid gap-1 text-[11px] font-bold">Slug<input name="slug" required class="h-9 border border-slate-200 px-3 text-xs"></label><label class="grid gap-1 text-[11px] font-bold">Sort order<input type="number" name="sort_order" value="0" required class="h-9 border border-slate-200 px-3 text-xs"></label><label class="flex items-center gap-2 text-[11px] font-bold"><input type="checkbox" name="is_active" value="1" checked> Active</label>
        <div data-language-tabs class="flex border-b border-slate-200">@foreach([['km','ខ្មែរ'],['en','English'],['zh','中文']] as [$locale,$label])<button type="button" data-language-tab="{{ $locale }}" class="border-b-2 px-3 py-2 text-[11px] font-bold {{ $loop->first?'is-active':'' }}">{{ $label }}</button>@endforeach</div>
        <div>@foreach(['km','en','zh'] as $locale)<div data-language-panel="{{ $locale }}" class="admin-language-panel grid gap-2" @if(!$loop->first) hidden @endif><input name="translations[{{ $locale }}][name]" placeholder="Category name" required class="h-9 border border-slate-200 px-3 text-xs"><textarea name="translations[{{ $locale }}][description]" rows="2" placeholder="Description" class="border border-slate-200 p-3 text-xs"></textarea></div>@endforeach</div>
        <button class="h-9 bg-[#173f88] text-xs font-bold text-white">Create category</button></div></form>
    <section class="border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-200 px-4 py-3"><h2 class="text-sm font-bold">Category list</h2></div><div class="divide-y divide-slate-100">@foreach($categories as $category)@php($texts=$category->translations->keyBy('locale'))<details class="group"><summary class="flex cursor-pointer list-none items-center gap-4 px-4 py-3 hover:bg-slate-50"><span class="font-bold">#{{ $category->id }}</span><span class="flex-1 font-semibold">{{ $category->translation('en')?->name }}</span><span class="text-[10px] text-slate-500">{{ $category->products_count }} products</span><span class="bg-blue-50 px-2 py-1 text-[10px] font-bold text-[#173f88]">{{ $category->is_active?'ACTIVE':'HIDDEN' }}</span><span>⌄</span></summary><form method="POST" action="{{ route('admin.categories.update',$category) }}" class="grid gap-3 border-t border-slate-100 bg-slate-50 p-4">@csrf @method('PUT')<div class="grid gap-3 sm:grid-cols-3"><input name="slug" value="{{ $category->slug }}" class="h-9 border border-slate-200 px-3 text-xs"><input type="number" name="sort_order" value="{{ $category->sort_order }}" class="h-9 border border-slate-200 px-3 text-xs"><label class="flex items-center gap-2 text-xs"><input type="checkbox" name="is_active" value="1" @checked($category->is_active)> Active</label></div><div><div data-language-tabs class="flex border-b border-slate-200">@foreach([['km','ខ្មែរ'],['en','English'],['zh','中文']] as [$locale,$label])<button type="button" data-language-tab="{{ $locale }}" class="border-b-2 px-3 py-2 text-[11px] font-bold {{ $loop->first?'is-active':'' }}">{{ $label }}</button>@endforeach</div>@foreach(['km','en','zh'] as $locale)<div data-language-panel="{{ $locale }}" class="admin-language-panel grid gap-2 pt-3" @if(!$loop->first) hidden @endif><input name="translations[{{ $locale }}][name]" value="{{ $texts->get($locale)?->name }}" required class="h-9 border border-slate-200 px-3 text-xs"><textarea name="translations[{{ $locale }}][description]" rows="2" class="border border-slate-200 p-2 text-xs">{{ $texts->get($locale)?->description }}</textarea></div>@endforeach</div><div class="flex justify-end"><button class="h-8 bg-[#173f88] px-4 text-[11px] font-bold text-white">Save category</button></div></form></details>@endforeach</div></section>
</div>
@endsection
