@extends('layouts.storefront')
@section('title', 'TrendShop — Cart')
@section('content')
<section class="min-h-[65vh] bg-[#f7f9fc] py-12 dark:bg-black"><div class="mx-auto max-w-5xl px-4"><h1 class="text-3xl font-bold">Shopping cart</h1><div class="mt-6 grid gap-4">
@forelse($cart->items as $item)
<article class="flex flex-col gap-4 border border-slate-200 bg-white p-4 dark:border-slate-800 dark:bg-[#0e1113] sm:flex-row sm:items-center"><img src="{{ $item->product->primaryImage()?->url() }}" alt="{{ $item->product->translation()?->name }}" class="size-24 object-contain"><div class="flex-1"><a href="{{ route('products.show', $item->product) }}" class="font-bold">{{ $item->product->translation()?->name }}</a><p class="mt-1 text-rose-500">${{ $item->unit_price }}</p></div><form method="POST" action="{{ route('cart.update', $item) }}" novalidate data-validate-form class="flex items-start gap-2">@csrf @method('PATCH')<div class="grid gap-1"><input type="number" name="quantity" min="1" max="{{ $item->product->stock_quantity }}" value="{{ $item->quantity }}" data-validation="required|number|min-value:1|max-value:{{ $item->product->stock_quantity }}" class="h-10 w-20 border border-slate-200 bg-transparent px-2 outline-none transition-colors focus:border-[#173f88] dark:border-slate-700"><x-form-error name="quantity" /></div><button class="h-10 border border-[#173f88] px-4 text-xs font-bold text-[#173f88]">Update</button></form><form method="POST" action="{{ route('cart.destroy', $item) }}">@csrf @method('DELETE')<button class="text-sm font-bold text-red-500">Remove</button></form></article>
@empty<p class="border border-slate-200 bg-white p-8 text-center text-slate-500 dark:border-slate-800 dark:bg-[#0e1113]">Your cart is empty.</p>@endforelse
</div>@if($cart->items->isNotEmpty())<div class="mt-6 border border-slate-200 bg-white p-6 dark:border-slate-800 dark:bg-[#0e1113]"><p class="text-right text-xl font-bold">Subtotal: ${{ number_format($cart->items->sum(fn($item) => $item->quantity * $item->unit_price), 2) }}</p>@if(auth()->user()->addresses->isNotEmpty())<form method="POST" action="{{ route('orders.store') }}" novalidate data-validate-form class="mt-4 flex flex-col items-end gap-3 sm:flex-row sm:justify-end">@csrf<input type="hidden" name="source" value="cart"><div class="grid w-full gap-1 sm:w-auto"><select name="address_id" data-validation="required" class="h-11 border border-slate-200 bg-transparent px-3 outline-none transition-colors focus:border-[#173f88] dark:border-slate-700">@foreach(auth()->user()->addresses as $address)<option value="{{ $address->id }}">{{ $address->label }} — {{ $address->city_province }} (${{ number_format($deliveryFees[$address->city_province] ?? 2, 2) }})</option>@endforeach</select><x-form-error name="address_id" /></div><button class="h-11 bg-[#173f88] px-6 font-bold text-white">Place order</button></form>@else<a href="{{ route('profile') }}#addresses" class="mt-4 flex h-11 items-center justify-center bg-[#173f88] px-6 font-bold text-white">Add delivery address</a>@endif</div>@endif</div></section>
@endsection
