{{-- Keep admin identity and quick actions in a compact fixed header. --}}
<header class="fixed inset-x-0 top-0 z-50 flex h-12 items-center border-t-2 border-[#173f88] bg-[#111827] text-white shadow">
    <div data-admin-brand class="flex w-[236px] items-center gap-2 px-3 transition-[width] duration-300"><button type="button" data-sidebar-open class="grid size-8 place-items-center rounded-sm transition-colors hover:bg-white/10 lg:hidden" aria-label="Open navigation"><x-admin.icon name="menu" class="size-5" /></button><img src="{{ asset('logo_web/image.png') }}" alt="TrendShop" class="size-7 shrink-0 object-contain"><span data-admin-brand-label class="whitespace-nowrap text-sm font-bold">TrendShop Admin</span></div>
    <div class="ml-auto flex h-full items-center">
        <a href="{{ route('products.index') }}" target="_blank" class="grid h-full w-11 place-items-center border-l border-white/10 bg-[#173f88] transition-colors hover:bg-[#2455a2]" title="Open storefront" aria-label="Open storefront"><x-admin.icon name="home" class="size-[18px]" /></a>
        <a data-admin-load href="{{ route('admin.notifications.index') }}" class="relative grid h-full w-11 place-items-center border-l border-white/10 transition-colors hover:bg-white/10" title="Notifications" aria-label="Notifications"><x-admin.icon name="bell" class="size-[18px]" />@if(($adminUnreadNotifications ?? 0) > 0)<span class="absolute right-1 top-1 grid min-w-4 place-items-center rounded-full bg-red-500 px-1 text-[9px] leading-4">{{ $adminUnreadNotifications }}</span>@endif</a>
        <div class="hidden h-full items-center gap-2 border-l border-white/10 bg-slate-700 px-4 sm:flex"><span class="grid size-7 place-items-center rounded-full bg-slate-500"><x-admin.icon name="user" class="size-4" /></span><span class="text-xs font-semibold">{{ auth('admin')->user()->name }}</span></div>
        <form method="POST" action="{{ route('admin.logout') }}" class="h-full">@csrf<button class="grid h-full w-11 place-items-center border-l border-white/10 transition-colors hover:bg-white/10" title="Sign out" aria-label="Sign out"><x-admin.icon name="logout" class="size-[18px]" /></button></form>
    </div>
</header>
